import type { PracticeCatalogEntry } from "./types"

export const GOOGLE_PRACTICE_CATALOG: readonly PracticeCatalogEntry[] = [
  {
    id: "google-style-typescript",
    title: "Google TypeScript Style Guide",
    category: "style",
    source: "Google Style Guides: tsguide.html",
    sourceUrl: "https://google.github.io/styleguide/tsguide.html",
    summary: "Standards for idiomatic, readable, and type-safe TypeScript code at Google scale.",
    detailedPrinciples: [
      "Use 2 spaces for indentation; never use tabs.",
      "Semicolons are mandatory at the end of statements.",
      "Use single quotes for string literals; backticks only for template interpolation or multi-line strings.",
      "Explicitly avoid 'any'; use 'unknown' when type is unconstrained, and narrow safely.",
      "Do not use non-null assertions (!) unless accompanied by explanatory comments or provably non-null invariants.",
      "Prefer 'const' over 'let'; never use 'var'.",
      "Favor named exports over default exports to ensure uniform naming across import sites.",
      "Use 'interface' for object structures and API contracts; use 'type' for unions, intersections, and primitives.",
      "Follow naming: camelCase for variables/functions, PascalCase for types/classes, UPPER_SNAKE_CASE for module constants.",
      "Format TODO comments with owner: // TODO(username): description.",
      "Organize imports into standard, external third-party, and workspace/local modules without star or aliased imports.",
    ],
    antiPatterns: [
      "any type annotations",
      "default export functions",
      "let variables that are never reassigned",
      "non-null assertion (!) without assertion guard",
      "TODO without username in parentheses",
      "console.log or debugger statements committed to production",
    ],
    recommendedPatterns: [
      "const result: unknown = fetchResult()",
      "export function computeStats(input: Data): Result",
      "// TODO(alice): Replace with streaming endpoint once v2 launches",
    ],
  },
  {
    id: "google-style-python",
    title: "Google Python Style Guide",
    category: "style",
    source: "Google Style Guides: pyguide.md",
    sourceUrl: "https://google.github.io/styleguide/pyguide.md",
    summary: "Conventions for Python code emphasizing maintainability, clarity, and safety.",
    detailedPrinciples: [
      "Use 2 spaces for indentation (Google Python style standard).",
      "Strict 80-character column limit.",
      "Docstrings must use Google Docstring format with Args, Returns, and Raises sections.",
      "Type annotations are mandatory on public function signatures and class definitions.",
      "Never use mutable default arguments (e.g. def func(items=[])); use None and initialize inside.",
      "Never use wildcard imports (from module import *); import module or specific symbols.",
      "Catch specific exceptions; never use bare 'except:' or catch generic 'Exception' without re-raising.",
      "Follow naming conventions: snake_case for functions/variables, PascalCase for classes, UPPER_SNAKE_CASE for constants.",
      "Import grouping: Standard library first, third-party libraries second, local application code third.",
    ],
    antiPatterns: [
      "def create_record(options={}) mutable default",
      "from typing import *",
      "bare except: pass",
      "Docstrings missing Args: or Returns: sections",
      "Lines exceeding 80 characters",
    ],
    recommendedPatterns: [
      "def fetch_user(user_id: str, timeout_sec: float | None = None) -> UserRecord:",
      "try: ... except KeyError as err: ...",
    ],
  },
  {
    id: "google-style-java",
    title: "Google Java Style Guide",
    category: "style",
    source: "Google Style Guides: javaguide.html",
    sourceUrl: "https://google.github.io/styleguide/javaguide.html",
    summary: "Google Java formatting, naming, and architectural conventions.",
    detailedPrinciples: [
      "Use 2 spaces for indentation; 100 column limit.",
      "Package statement must not be line-wrapped.",
      "No wildcard imports (static or non-static); import each symbol explicitly.",
      "Class member ordering: static fields, instance fields, constructors, methods.",
      "Always use @Override annotation on overriding methods.",
      "Never ignore caught exceptions; catch block must contain action or '// expected' comment.",
      "Identifiers: UpperCamelCase for classes, lowerCamelCase for methods/variables, UPPER_SNAKE_CASE for constants.",
      "Javadoc mandatory on public classes and public methods.",
    ],
    antiPatterns: [
      "import java.util.*;",
      "catch (IOException e) {} empty catch without comment",
      "Missing @Override on interface implementations",
      "Variable names with single character abbreviations",
    ],
    recommendedPatterns: [
      "@Override public String toString() { return name; }",
      "catch (NoSuchElementException expected) { /* expected when queue empty */ }",
    ],
  },
  {
    id: "google-style-cpp",
    title: "Google C++ Style Guide",
    category: "style",
    source: "Google Style Guides: cppguide.html",
    sourceUrl: "https://google.github.io/styleguide/cppguide.html",
    summary: "C++ conventions designed to avoid undefined behavior, manage memory safely, and ensure clarity.",
    detailedPrinciples: [
      "Use 2 spaces for indentation.",
      "Header guards must follow <PROJECT>_<PATH>_<FILE>_H_ format or #pragma once.",
      "Include What You Use (IWYU): include every header providing a symbol used directly.",
      "Include order: related header, C system headers, C++ standard library, other libraries, project headers.",
      "Use std::unique_ptr and std::shared_ptr for dynamic memory; avoid raw owning pointers.",
      "Use nullptr instead of 0 or NULL.",
      "Never use 'using namespace std;' in header files or file global scope.",
      "Const correctness: declare functions and parameters const whenever possible.",
      "Naming: PascalCase for types, camelCase for functions, kConstantName for constants, variable_name_ for private member variables.",
    ],
    antiPatterns: [
      "using namespace std;",
      "int* ptr = new int(5); delete ptr;",
      "NULL or 0 for null pointers",
      "Missing header guard",
    ],
    recommendedPatterns: [
      "auto record = std::make_unique<Record>(id);",
      "constexpr int kMaxBatchSize = 100;",
      "const std::string& name() const { return name_; }",
    ],
  },
  {
    id: "google-style-go",
    title: "Google Go Style Guide",
    category: "style",
    source: "Google Style Guides: go/guide.md",
    sourceUrl: "https://google.github.io/styleguide/go/",
    summary: "Idiomatic Go conventions focusing on error handling, concurrency, and API ergonomics.",
    detailedPrinciples: [
      "Errors must be returned as the last value and checked immediately; never discard with '_'.",
      "Wrap errors with context using fmt.Errorf('...: %w', err).",
      "context.Context must always be the first parameter in functions that perform I/O or background work.",
      "Receiver names must be short (1-2 letters) and consistent across all methods of the type.",
      "Package names must be short, lowercase, single words without underscores or mixed caps.",
      "Keep interfaces small (1-2 methods) and define them on the consumer side.",
      "Use table-driven tests for test suite consistency.",
      "Do not use panic() for ordinary control flow or error reporting.",
    ],
    antiPatterns: [
      "_ = file.Close()",
      "func (this *Server) Start()",
      "func Process(data []byte, ctx context.Context)",
      "panic('record not found')",
    ],
    recommendedPatterns: [
      "func (s *Server) Process(ctx context.Context, req *Request) (*Response, error)",
      "if err != nil { return nil, fmt.Errorf('executing query: %w', err) }",
    ],
  },
  {
    id: "google-style-shell",
    title: "Google Shell Style Guide",
    category: "style",
    source: "Google Style Guides: shellguide.md",
    sourceUrl: "https://google.github.io/styleguide/shellguide.md",
    summary: "Safety, robust error handling, and portability for bash scripts.",
    detailedPrinciples: [
      "Bash only; use #!/bin/bash or #!/usr/bin/env bash.",
      "Always set error traps early: set -euo pipefail.",
      "Always double-quote variable expansions and command substitutions: \"${var}\", \"$(command)\".",
      "If a script exceeds 100 lines or requires complex data structures, rewrite in Python or Go.",
      "Wrap procedural execution in a main() function and invoke via: main \"$@\".",
      "Use 'local' for all function-scoped variables.",
      "Naming: lower_snake_case for functions and local variables; UPPER_SNAKE_CASE for environment constants.",
    ],
    antiPatterns: [
      "#!/bin/sh without strict flags",
      "echo $UNQUOTED_VAR",
      "rm -rf $DIR/*",
      "Global variables modified across functions without local keyword",
    ],
    recommendedPatterns: [
      "#!/usr/bin/env bash\nset -euo pipefail\n\nmain() {\n  local input_file=\"${1}\"\n  ...\n}\nmain \"$@\"",
    ],
  },
  {
    id: "google-style-html-css",
    title: "Google HTML/CSS Style Guide",
    category: "style",
    source: "Google Style Guides: htmlcssguide.html",
    sourceUrl: "https://google.github.io/styleguide/htmlcssguide.html",
    summary: "Semantic HTML5 and maintainable CSS conventions.",
    detailedPrinciples: [
      "Use 2 spaces for indentation.",
      "All HTML tags and attributes must be in lowercase.",
      "Double quotes for HTML attribute values.",
      "Never use inline styles (style=\"...\"); use stylesheet classes.",
      "Use lowercase kebab-case for CSS class names.",
      "Do not use ID selectors for CSS styling.",
      "Always specify <!DOCTYPE html> at the beginning of HTML documents.",
    ],
    antiPatterns: [
      "<DIV STYLE=\"color: red;\">",
      "#submit-button { margin: 10px; }",
      "uppercase HTML tags or attributes",
    ],
    recommendedPatterns: [
      "<!DOCTYPE html>\n<html lang=\"en\">\n<head>...",
      ".nav-item-active { font-weight: 600; }",
    ],
  },
  {
    id: "google-style-docguide",
    title: "Google Developer Documentation Style Guide",
    category: "documentation",
    source: "Google Style Guides: docguide/best_practices.md",
    sourceUrl: "https://google.github.io/styleguide/docguide/",
    summary: "Clarity, active voice, and precision in developer technical documentation.",
    detailedPrinciples: [
      "Write in the active voice and present tense.",
      "Address the reader in the second person ('you').",
      "Link text must be descriptive of the target; ban 'click here', 'here', or raw unlinked URLs.",
      "Headings must follow a strict hierarchy without skipping levels (H1 -> H2 -> H3).",
      "All code blocks in Markdown must declare a language identifier.",
      "Focus on what the developer needs to do, omitting conversational filler.",
    ],
    antiPatterns: [
      "Click here to read more",
      "``` without language identifier",
      "Skipping from # H1 to ### H3",
      "Passive voice: 'The request is processed by the server'",
    ],
    recommendedPatterns: [
      "See the [authentication tutorial](auth.md) for details.",
      "```typescript\nconst token = createToken()\n```",
      "The server processes the request.",
    ],
  },
  {
    id: "google-eng-code-review",
    title: "Google Code Review Guidelines",
    category: "eng-practices",
    source: "Google Engineering Practices: review/reviewer/standard.md",
    sourceUrl: "https://google.github.io/eng-practices/review/reviewer/standard.html",
    summary: "The canonical code review standard: continuous improvement and team velocity.",
    detailedPrinciples: [
      "The Standard: Approve a change once it definitely improves the overall code health of the system, even if not perfect.",
      "Favor forward progress over seeking perfection; do not block changes for stylistic preferences.",
      "Mentoring is an integral part of code review, but approval should not be withheld purely for optional mentoring suggestions.",
      "Speed of reviews: Provide feedback within one business day; keep review turnarounds rapid to prevent context switching.",
      "Respectful comments: Critique the code, not the person. Provide rationale and concrete alternatives.",
      "Label non-blocking suggestions clearly with 'nit:' so authors know they do not block submission.",
    ],
    antiPatterns: [
      "Blocking approval for personal stylistic preferences that conform to the style guide",
      "Letting review comments sit unanswered for days",
      "Vague criticism without actionable recommendations",
    ],
    recommendedPatterns: [
      "In general, reviewers should favor approving a CL once it improves system health.",
      "nit: consider inlining this helper since it is only called once.",
    ],
  },
  {
    id: "google-eng-small-cls",
    title: "Google Small CLs and CL Descriptions",
    category: "eng-practices",
    source: "Google Engineering Practices: review/developer/small-cls.md",
    sourceUrl: "https://google.github.io/eng-practices/review/developer/small-cls.html",
    summary: "Decomposition into atomic changes and informative changelist descriptions.",
    detailedPrinciples: [
      "Keep CLs small: A CL should represent one self-contained, atomic logical change.",
      "Target change size: Typically under 200-400 lines of code; changes exceeding 500 lines or 15 files should be split into smaller milestones.",
      "CL Description line 1: Imperative summary under 72 characters explaining WHAT the change does.",
      "CL Description line 2: Blank line separating summary from body.",
      "CL Description body: Detailed explanation of WHY the change is needed, context, and alternatives considered.",
      "Include explicit test plan ('Tested: bun test ...' or unit test references).",
    ],
    antiPatterns: [
      "Giant 2,000-line monolithic PRs mixing refactoring and new features",
      "One-line commit messages like 'fix bug' or 'updates'",
      "PRs with no test verification notes",
    ],
    recommendedPatterns: [
      "Add idempotent token refresh retry mechanism\n\nWhen provider tokens expire during stream execution, re-authenticate with exponential backoff.\n\nTested: bun test test/ocx/auth.test.ts",
    ],
  },
  {
    id: "google-testing-doctrine",
    title: "Google Testing Doctrine & Testing on the Toilet",
    category: "testing",
    source: "Software Engineering at Google (Chapters 11-14) & Testing on the Toilet",
    sourceUrl: "https://abseil.io/resources/swe-book/html/ch11.html",
    summary: "Reliable, hermetic, and maintainable automated test doctrine.",
    detailedPrinciples: [
      "Test Sizes: Small (<60s, in-memory, hermetic, zero network/disk), Medium (<300s, localhost, single machine), Large (distributed, E2E).",
      "DAMP over DRY in tests: Tests must be Descriptive And Meaningful Phrases; avoid hiding setup in deep helper abstractions.",
      "Test Behaviors, Not Methods: Structure tests around observable behaviors and outcomes, not method names.",
      "Don't Put Logic in Tests: Never put loops (for/while), conditionals (if/switch), or complex math in test bodies.",
      "Test Doubles Policy: Prefer Real Objects > Hermetic Fakes > Stubs > Mocks as a last resort.",
      "Never mock types you do not own (e.g. standard library, external network clients).",
      "Respect @DoNotMock on value objects, data records, and domain models.",
      "Eliminate flakiness: Ban real sleeps (setTimeout, Thread.sleep, time.Sleep) in tests; use virtual clocks or explicit completion triggers.",
      "The Beyoncé Rule: 'If you liked it you should have put a test on it.' Infrastructure breaks without tests are not bugs in infrastructure.",
    ],
    antiPatterns: [
      "for (const item of items) { expect(item).toBe(...) } inside test function",
      "if (condition) { expect(a).toBe(b) } branching inside test",
      "await new Promise(r => setTimeout(r, 1000)) in unit tests",
      "Mocking third-party database drivers or standard file systems",
      "Testing private methods directly instead of public contracts",
    ],
    recommendedPatterns: [
      "test('returns cached token when token has not expired', () => { ... })",
      "Use fake in-memory repository instead of complex mock expectations",
    ],
  },
  {
    id: "google-api-design",
    title: "Google API Design Guide (AIPs)",
    category: "api-design",
    source: "Google Cloud API Design Guide & AIP (google.aip.dev)",
    sourceUrl: "https://google.aip.dev",
    summary: "Resource-oriented API design conventions for REST and gRPC services.",
    detailedPrinciples: [
      "Resource-Oriented Architecture: Organize APIs into collections and resources (e.g. /v1/publishers/{publisher}/books/{book}).",
      "Standard Methods: Strictly adhere to Get, List, Create, Update, Delete semantics.",
      "Custom Methods: Use ':customVerb' suffix (e.g. /v1/documents/12:archive) with POST or GET.",
      "Pagination: List endpoints must accept 'page_size' (integer) and 'page_token' (string), returning 'next_page_token'.",
      "Partial Updates: Update methods must use FieldMask ('update_mask') instead of full object overwrites.",
      "Canonical Errors: Use standard status codes (NotFound, InvalidArgument, PermissionDenied, etc.) with structured details.",
      "Naming: snake_case in protocol buffers, camelCase in JSON representations, UPPER_SNAKE_CASE in enum values.",
    ],
    antiPatterns: [
      "GET /v1/deleteUser?id=123",
      "Unbounded list endpoints without page_size or page_token",
      "Returning HTTP 200 with error messages embedded in JSON payload",
      "Exposing internal database IDs or stack traces to clients",
    ],
    recommendedPatterns: [
      "GET /v1/users?page_size=50&page_token=abc",
      "PATCH /v1/users/123?update_mask=displayName,email",
    ],
  },
  {
    id: "google-swe-architecture",
    title: "Software Engineering at Google: Architecture & Hyrum's Law",
    category: "architecture",
    source: "Software Engineering at Google (Winters, Manshreck, Wright)",
    sourceUrl: "https://abseil.io/resources/swe-book/html/ch01.html",
    summary: "Architectural sustainability over time, scale, and organizational change.",
    detailedPrinciples: [
      "Hyrum's Law: All observable behaviors of an API will eventually be depended upon; encapsulate internal state aggressively.",
      "Deprecation Lifecycle: Deprecate with @deprecated / // Deprecated: comment, specifying migration path and target milestone.",
      "Prevent Backsliding: Disallow adding new callers to already deprecated APIs through automated checks.",
      "Fine-Grained Modules and 1:1:1 Rule: Keep modules cohesive; avoid cyclic dependencies between packages.",
      "Tricorder Static Analysis Standard: Static analysis warnings must have high signal (>90% developer acceptance rate) or be removed.",
      "Hermetic Builds: Builds must depend strictly on explicitly declared inputs, producing bit-for-bit reproducible artifacts.",
    ],
    antiPatterns: [
      "Exposing internal implementation classes in public package exports",
      "Adding new calls to deprecated methods",
      "Circular package import graphs",
      "Linter rules with high false-positive rates causing developer alert fatigue",
    ],
    recommendedPatterns: [
      "/** @deprecated Use {@link #createNewSession(SessionConfig)} instead. Will be removed in v2.4. */",
      "Internal package boundaries with private visibility",
    ],
  },
  {
    id: "google-security-practices",
    title: "Google Secure Coding Best Practices",
    category: "security",
    source: "Google Security & Software Engineering at Google",
    sourceUrl: "https://abseil.io/resources/swe-book",
    summary: "Secure by Design principles to eliminate common vulnerability classes.",
    detailedPrinciples: [
      "SafeSQL: Never concatenate or interpolate user input directly into SQL queries; use parameterized queries.",
      "SafeHTML: Never inject raw HTML via innerHTML or unescaped templates; use type-safe contextual auto-escaping.",
      "Secret Management: Never commit credentials, private keys, or API tokens to source control.",
      "Logging Hygiene: Never log sensitive parameters, passwords, authorization tokens, or personal identifying info.",
      "Defense in Depth and Least Privilege: Validate inputs at component boundaries; grant minimum necessary permissions.",
    ],
    antiPatterns: [
      "db.execute(`SELECT * FROM users WHERE id = '${userId}'`)",
      "element.innerHTML = userInput",
      "const API_KEY = 'AIzaSy...'",
      "console.log('Login attempt:', { username, password })",
    ],
    recommendedPatterns: [
      "db.query('SELECT * FROM users WHERE id = $1', [userId])",
      "element.textContent = userInput",
      "const apiKey = process.env.API_KEY",
    ],
  },
]
